### ISSUE TITLE
Coordinator crashes with java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by vikulin** [iotaledger/compass#118] opened 2019-05-25 20:41 UTC
### Bug description
2019-05-25 20:33:07:758 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: PMGBLDEMQVLXEYWMY9VTKDROHRK9AKDKXFHEPFMFKGLADIPORXTPHGXPIOOHGVUCTRAFGLNQPCUVWR999 Branch: PMGBLDEMQVLXEYWMY9VTKDROHRK9AKDKXFHEPFMFKGLADIPORXTPHGXPIOOHGVUCTRAFGLNQPCUVWR999
2019-05-25 20:33:08:061 +0000 [main] INFO org.iota.compass.Coordinator - Broadcast milestone: 4094
2019-05-25 20:33:08:061 +0000 [main] INFO org.iota.compass.Coordinator - Depth: 3 -> 3
2019-05-25 20:33:08:062 +0000 [main] INFO org.iota.compass.Coordinator - stored index 4094
2019-05-25 20:34:08:081 +0000 [main] INFO org.iota.compass.Coordinator - Issuing milestone: 4095
2019-05-25 20:34:08:081 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: DZKFSEXBITWEYBAWJJBNSUHVTNREJPTGFVDHWFVXEMVJFDGOUSLSJWAPJAHGPPJUXJ9L9LETFGZFGU999 Branch: DZKFSEXBITWEYBAWJJBNSUHVTNREJPTGFVDHWFVXEMVJFDGOUSLSJWAPJAHGPPJUXJ9L9LETFGZFGU999
2019-05-25 20:34:08:306 +0000 [main] INFO org.iota.compass.Coordinator - Broadcast milestone: 4095
2019-05-25 20:34:08:306 +0000 [main] INFO org.iota.compass.Coordinator - Depth: 3 -> 3
2019-05-25 20:34:08:307 +0000 [main] INFO org.iota.compass.Coordinator - stored index 4095
2019-05-25 20:35:08:324 +0000 [main] INFO org.iota.compass.Coordinator - Issuing milestone: 4096
2019-05-25 20:35:08:324 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: LKQSGPOWNVW99VIIYPEWCTVNOOUCBTPDRGWXKTZUSOFVTMPHVKNIMFJAVNOYWIEUATYTUQZRPKDNVX999 Branch: LKQSGPOWNVW99VIIYPEWCTVNOOUCBTPDRGWXKTZUSOFVTMPHVKNIMFJAVNOYWIEUATYTUQZRPKDNVX999
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 4097, Size: 4096
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.iota.compass.MilestoneDatabase.siblings(MilestoneDatabase.java:130)
        at org.iota.compass.MilestoneDatabase.createMilestone(MilestoneDatabase.java:174)
        at org.iota.compass.Coordinator.createAndBroadcastMilestone(Coordinator.java:375)
        at org.iota.compass.Coordinator.start(Coordinator.java:325)
        at org.iota.compass.Coordinator.main(Coordinator.java:127)

### Hardware Spec
Ubuntu 18.0.4 x64

### Steps To Reproduce
Steps to reproduce are unkown

**Comment by GalRogozinski** [comment] 2019-05-26 07:25
Your compass configuration (probably depth) is not compatible with the layers you created.

The action item from this is to create a better error message

**Comment by jakubcech** [comment] 2019-05-30 15:01
Have you managed to resolve this @vikulin?

**Comment by vikulin** [comment] 2019-05-31 07:47
No, it looks like the coo throws the erorr when it gets a final milestone.

чт, 30 мая 2019 г. в 18:01, Jakub Cech <notifications@github.com>:

**Comment by karimodm** [comment] 2019-06-03 10:08
@vikulin can you please post the configuration you used to generate the Merkle Layers and also detail how are you running compass?

**Comment by vikulin** [comment] 2019-06-03 10:16
I do not run compass I run only layer calculation: ./01_calculate_layers.sh

My config.json:

{
  "seed":
"HTCRDHFEYGCZEKMVZPPZJFOPSCMYMHRITIMAIBYMHXESUZWTMNGMRLZNGAWILELGGUDJWVNNKOPMBAAHKD",
  "powMode": "CURLP81",
  "sigMode": "CURLP27",
  "security": 1,
  "depth": 24,
  "milestoneStart": 0,
  "mwm": 9,
  "tick": 60000,
  "host": "http://localhost:14265"
}

пн, 3 июн. 2019 г. в 13:08, Andrea V <notifications@github.com>:

**Comment by karimodm** [comment] 2019-06-03 10:25
The log extract you posted in the first comment to the issue shows a Compass run!
```
2019-05-25 20:33:07:758 +0000 [main] INFO org.iota.compass.Coordinator - Trunk: PMGBLDEMQVLXEYWMY9VTKDROHRK9AKDKXFHEPFMFKGLADIPORXTPHGXPIOOHGVUCTRAFGLNQPCUVWR999 Branch: PMGBLDEMQVLXEYWMY9VTKDROHRK9AKDKXFHEPFMFKGLADIPORXTPHGXPIOOHGVUCTRAFGLNQPCUVWR999
2019-05-25 20:33:08:061 +0000 [main] INFO org.iota.compass.Coordinator - Broadcast milestone: 4094
[...]
```

The exception seems to be thrown by Compass itself. Can you please clean your data folders and start over with the latest `master` revision and see if you can still reproduce?

**Comment by vikulin** [comment] 2019-06-03 10:31
No, I won't run it anymore having no time to continue with this. Could you
please reproduce it by yourself? I think the issue appears when milestone
index reaches the max value. I had depth = 8 or so.

пн, 3 июн. 2019 г. в 13:25, Andrea V <notifications@github.com>:

**Comment by karimodm** [comment] 2019-06-04 09:22
This being the case I think this is a duplicate of https://github.com/iotaledger/compass/issues/120 . I think we should close it in favour of that one if you don't have any additional information.

**Comment by vikulin** [comment] 2019-06-04 09:29
As I said:
> I think the issue appears when milestone index reaches the max value. I
had depth = 8 or so
This is enough to reproduce the issue.

вт, 4 июн. 2019 г. в 12:22, Andrea V <notifications@github.com>:

**Closed** 2019-07-18 07:40 UTC

**Comment by lyudad** [comment] 2020-02-27 22:14
Have same issue 
 "security": 1,
  "depth": 16,
  "milestoneStart": 0,
  "mwm": 9,
  "tick": 60000,

**Comment by lyudad** [comment] 2020-02-29 14:38
Everything fine, seed was wrong
