### ISSUE TITLE
Build did NOT complete successfully

### ISSUE THREAD

**Issue by xu926419** [iotaledger/compass#141] opened 2020-01-05 21:41 UTC
An error occurred during the fetch of repository 'java_base':
   Pull command failed: E0106 05:36:33.649055   19313 retry_.py:106] Retrying after exception .

I have an error, can you help me? Thank you very much.

**Comment by xu926419** [comment] 2020-01-05 22:04
Analysis of target '//docker:signature_source_server' failed; build aborted: no such package '@java_base//image': Pull command failed: E0106 05:56:33.964715   19819 retry_.py:106] Retrying after exception .

**Comment by xu926419** [comment] 2020-01-05 22:05
I provide more error information in the second comment.

**Comment by karimodm** [comment] 2020-01-06 13:17
How are you trying to build? What version of Bazel are you using?

**Comment by xu926419** [comment] 2020-01-07 12:38
I show my four attempts as below. Thanks for your help.

In the beginning，I try bazel run //docker:layers_calculator, but it failed.(The version of Bazel is 0.23.0) The error is as follows:
ERROR: An error occured during the fetch of repository 'java_base': Pull command failed: Timed out.
ERROR: /home/hengji/compass/docker/BUILD:3:1: //docker:layers_calculator depends on @java_base//image:image in repository @java_base which failed to fetch. no such package '@java_base//image': Pull command failed: Timed out
ERROR: Analysis of target '//docker:layers_calculator' failed;build aborted: no such package '@java_base//image'

Then, I try on another machine. I also failed. (The version of Bazel is 0.23.0) The error is as follows:
ERROR: /home/hengji/compass/docker/BUILD:3:1: no such package '@java_base//image': Pull command failed: E1231 04:55:22.425658 13839 retry_.py:106] Retrying afer exception.
E1231 04:56:05.436449 13839 retry_.py:106] Retrying afer exception.
F1231 04:56:49.446168 13839 __main__.py:147] Error pulling and saving image gcr.io/distroless/java@sha256:bb...
ERROR: Analysis of target '//docker:layers_calculator' failed;build aborted: no such package '@java_base//image' :Pull command failed: E1231 04:55:22.425658 13839 retry_.py:106] Retrying after exception.
E1231 04:56:05.436449 13839 retry_.py:106] Retrying afer exception.
F1231 04:56:49.446168 13839 __main__.py:147] Error pulling and saving image gcr.io/distroless/java@sha256:bb...

Next, I found #130 is similar to mine. So I try it.(The version of Bazel is 0.23.0)
There is ./bazel and ./cache under the path $HOME, and there is a folder bazel under within the folder ./cache.
I remove the folder bazel from the ./cache, and then I try 'bazel build ...' under the path ~/compass. 
ERROR: /home/hengji/compass/docker/BUILD:27:1 no such package '@java_base//image': Pull command failed: E0104 18:14:24 4071 retry_.py:106] Retrying after exception.
E0104 18:15:07.475898 4071 retry_.py:106] Retrying after exception.
F0104 18:15:51.501733 4071 __main__.py:147] Error pulling and saving image gcr.io/distroless/java@sha256:bb...
ERROR: Analysis of target '//docker:signature_source_server' failed; build aborted: no such package '@java_base//image': Pull command failed: E0104 18:14:24.466341 4071 retry_.py:106] Retrying after exception.
Failed: Build did NOT complete successfully (70 package loaded,1269 targets configured)
Fetching @java_base; fetching 1939s
Fetching @io_netty_netty_tcnative_boringssl_static; fetching 1889s
Fetching @com_google_code_gson_gson; fetching 1806s
Fetching @io_netty_netty_transport; fetching 1804s

Later, I found #137 mentioned the update about compass for newer bazel version. So I tried on a new vitural machine with bazel-0.28.1, and try 'bazel build ...' before 'bazel run //docker:layers_calculator'.But I still failed, and the error is similar to the previous one.

**Comment by GalRogozinski** [comment] 2020-02-10 09:04
I tried to have a look today. Due to constraints I couldn't invest too much time on this issue. It seemed to be harder than I anticipated.Please use docker images from here in the meanwhile: https://hub.docker.com/r/iotacafe/compass/tags
--

**Comment by GalRogozinski** [comment] 2020-04-20 09:59
Fixed by #150

**Comment by GalRogozinski** [comment] 2020-04-20 10:00
Duplicate of #142

**Closed by GalRogozinski** 2020-04-20 09:59 UTC
